/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as PreturiRouteImport } from './routes/preturi'
import { Route as ProcesRouteImport } from './routes/proces'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as TestimonialeRouteImport } from './routes/testimoniale'
import { Route as ZonaDeAcoperireRouteImport } from './routes/zona-de-acoperire'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const PreturiRoute = PreturiRouteImport.update({
  id: '/preturi',
  path: '/preturi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesRoute = ProcesRouteImport.update({
  id: '/proces',
  path: '/proces',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialeRoute = TestimonialeRouteImport.update({
  id: '/testimoniale',
  path: '/testimoniale',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaDeAcoperireRoute = ZonaDeAcoperireRouteImport.update({
  id: '/zona-de-acoperire',
  path: '/zona-de-acoperire',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/preturi': typeof PreturiRoute
  '/proces': typeof ProcesRoute
  '/servicii': typeof ServiciiRoute
  '/testimoniale': typeof TestimonialeRoute
  '/zona-de-acoperire': typeof ZonaDeAcoperireRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/preturi': typeof PreturiRoute
  '/proces': typeof ProcesRoute
  '/servicii': typeof ServiciiRoute
  '/testimoniale': typeof TestimonialeRoute
  '/zona-de-acoperire': typeof ZonaDeAcoperireRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/preturi': typeof PreturiRoute
  '/proces': typeof ProcesRoute
  '/servicii': typeof ServiciiRoute
  '/testimoniale': typeof TestimonialeRoute
  '/zona-de-acoperire': typeof ZonaDeAcoperireRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/despre'
    | '/preturi'
    | '/proces'
    | '/servicii'
    | '/testimoniale'
    | '/zona-de-acoperire'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/despre'
    | '/preturi'
    | '/proces'
    | '/servicii'
    | '/testimoniale'
    | '/zona-de-acoperire'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/despre'
    | '/preturi'
    | '/proces'
    | '/servicii'
    | '/testimoniale'
    | '/zona-de-acoperire'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespreRoute: typeof DespreRoute
  PreturiRoute: typeof PreturiRoute
  ProcesRoute: typeof ProcesRoute
  ServiciiRoute: typeof ServiciiRoute
  TestimonialeRoute: typeof TestimonialeRoute
  ZonaDeAcoperireRoute: typeof ZonaDeAcoperireRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preturi': {
      id: '/preturi'
      path: '/preturi'
      fullPath: '/preturi'
      preLoaderRoute: typeof PreturiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proces': {
      id: '/proces'
      path: '/proces'
      fullPath: '/proces'
      preLoaderRoute: typeof ProcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoniale': {
      id: '/testimoniale'
      path: '/testimoniale'
      fullPath: '/testimoniale'
      preLoaderRoute: typeof TestimonialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona-de-acoperire': {
      id: '/zona-de-acoperire'
      path: '/zona-de-acoperire'
      fullPath: '/zona-de-acoperire'
      preLoaderRoute: typeof ZonaDeAcoperireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespreRoute: DespreRoute,
  PreturiRoute: PreturiRoute,
  ProcesRoute: ProcesRoute,
  ServiciiRoute: ServiciiRoute,
  TestimonialeRoute: TestimonialeRoute,
  ZonaDeAcoperireRoute: ZonaDeAcoperireRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
